name: Playwright Tests
on:
  pull_request:
  schedule:
    - cron: "18 18 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4
        with:
          version: 11
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm ci
      - name: Build project
        if: github.event_name == 'pull_request'
        run: pnpm run build
      - name: Run Playwright tests for local server
        if: github.event_name == 'pull_request'
        run: pnpm run test
        env:
          USE_DEPLOYED_SITE: "false"
      - name: Run Playwright tests for deployed site
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: pnpm run test
        env:
          USE_DEPLOYED_SITE: "true"
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
